### ISSUE TITLE
smart_autocomplete table remains empty

### ISSUE THREAD

**Issue by ychaouche** [teonsystems/roundcube-plugin-smart-autocomplete#3]
Hello,
I have installed smart_autocomplete and applied the 1.1.4 patch. I have sent numerous emails (more than 10) and the smart_autocomplete table remains empty and plugin isn't learning anything.

Any clues ?

**Comment by bostjan** [comment]
Hello Yassine,

not at the first sight.

Questions:
- Do you have your addresses already in your addressbook?
- when composing new message, open up developer tools, head to Network tab and see if request gets passed to server when you accept a suggestion. If so, what is the server's response?

Keep in mind that if you do not accept email address suggestion by selecting it, it will not be logged as an accepted suggestion. Also, this plugin does not do address autocollection for you.

**Comment by ychaouche** [comment]
Hello bostjan and sorry for late reply. I don't see anything in the NET tab so there are no queries sent to the server. Maybe there are some javascript files that need to be patched THEN minimized ? (I already saw this kind of behaviour on zimbra).

**Comment by ychaouche** [comment]
I have added some debug prints in the javascript code, I don't know if this can help you 

http://i.imgur.com/YgAkeXO.png

**Comment by ychaouche** [comment]
I have added some print statements in the PHP code and found out that the called function will skip because search_string is empty

```
   public function register_accepted_suggestion ()
    {
        $search_string   = rcube_utils::get_input_value('search_string',   rcube_utils::INPUT_GPC);
        $accepted_type   = rcube_utils::get_input_value('accepted_type',   rcube_utils::INPUT_GPC);
        $accepted_id     = rcube_utils::get_input_value('accepted_id',     rcube_utils::INPUT_GPC);
        $accepted_email  = rcube_utils::get_input_value('accepted_email',  rcube_utils::INPUT_GPC);
        $accepted_source = rcube_utils::get_input_value('accepted_source', rcube_utils::INPUT_GPC);
        // Yassine 2016/09/20
        file_put_contents('/tmp/smart',"Accepted id = " . $accepted_id . "\n", FILE_APPEND);
        file_put_contents('/tmp/smart',"Search string = " . $search_string . "\n", FILE_APPEND);

        // Skip if search string is shorter than what is configured 
        if (strlen($search_string) < $this->min_search_string_length) {
            return;
        }

```

The log file shows that search_string is empty, hence the if condition will pass and the function will return : 
```

root@messagerie[10.10.10.20] /tmp # tail -f smart
Accepted id = 1147                                                                                                     
Search string =
root@messagerie[10.10.10.20] /tmp # 
```

**Comment by ychaouche** [comment]
Ok apparently my problem is that I need to recreate the app.min.js after applying the patch. Will try to find a way to do that.

**Comment by ychaouche** [comment]
Compressed it online with https://jscompress.com/, now the table is populated 
http://i.imgur.com/zNpDKYG.png
and the calls seem to go fine ! 
http://i.imgur.com/fCvKAHr.png

One detail though is that the email address is empty in the database. Is that OK ?

**Comment by bostjan** [comment]
This accepted_email=NULL could be a bug, I will have to check it out. Please file it separately if needed.

Also, suggestions (best in form of patches:) for plugin improvements will be greatly appreciated. I hope you like it so far.

I have put off maintenance of this for some time, as I was waiting for required patches to be accepted into RC upstream. Did not check that lately, but I think they are getting through. Once that is done, no more RC patching to install this plugin:
https://github.com/roundcube/roundcubemail/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Abostjan

Good debugging btw :+1:

**Comment by ychaouche** [comment]
Hello @bostjan 

Just as a follow I am upgrading to 1.2.4 and the patches aren't present in the app.js source code. smart_autcomplete still doesn't work. Will apply the 1.2.0 patch and see if that helps.

**Comment by ychaouche** [comment]
2 hunks of autocomplete.inc didn't pass

```
root@messagerie-secours[10.10.10.20] /var/www/roundcubemail-1.2.4 # patch -p1 < plugins/smart_autocomplete/patches/smart_autocomplete-roundcube-1.2.0-patch.diff 
patching file program/js/app.js
Hunk #1 succeeded at 5206 (offset 24 lines).
Hunk #2 succeeded at 5216 (offset 24 lines).
Hunk #3 succeeded at 5260 (offset 24 lines).
patching file program/steps/mail/autocomplete.inc
Hunk #1 FAILED at 58.
Hunk #2 FAILED at 92.
Hunk #3 succeeded at 141 (offset 6 lines).
Hunk #4 succeeded at 158 (offset 6 lines).
Hunk #5 succeeded at 181 (offset 6 lines).
2 out of 5 hunks FAILED -- saving rejects to file program/steps/mail/autocomplete.inc.rej
root@messagerie-secours[10.10.10.20] /var/www/roundcubemail-1.2.4 # 
```

**Comment by ychaouche** [comment]
The plugin works after applying the patches or modifying code by hand, then minifying again.
